# Generated by Django 5.2 on 2025-04-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_specialty_alter_doctors_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reste_token',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reste_token',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
